print('name: Raviteja R')
print('Mobile: 7675025059')
print('Landmark Rewards No: 6722087428' "\n")
str = "Tax Invoice/Bill of Supply"
print(str.center(10, ' '))
print('ITEM/HSN/Desc MRP Disc% RSP QTY T%')
print('1000007248398  62059090 KNIT TPO SL RE')
print('299.00    0.00    299.00  1 A,B')
print('Total Amt           299.00')
print('Total Rounded       299.00')
print('Rounded Off Amt       0.00')
print('cash                500.00')
print('Total Tender        500.00')
print('Change due         -201.00')
print('Total Number of Items/Qty:   1/1')
print('-------------------------------------------')
print(   "TAx Details"   )
print('Tax Desc           Taxble     Tax')
print('A CGST- (2.5%)     284.76     7.12')
print('B SGST- (2.5%)     284.76     7.12')
print('                             -------')
print('Total Tax value               14.24')
print('-------------------------------------------')
print('Str:02003 Reg:102 Train:0024106 Till:102')
print('14-Feb-2019 21:05:43  Cashier:1046876')
print('Invoice No:020031020024106')
print('Total savings:  0.00')
print('--------------------------------------------')
print('Thank you for shopping with us')
print('*Terms & Conditions apply.See over leaf' "\n" 'Tax incl of addt.taxes applicable if any')
print('--------------------------------------------')
print('Merchandise can be exchanged with in 30 days' "\n" 'from the date of purchase provided the'"\n" 'merchandise is unused and in sealable' "\n" 'condition, along with original product tag' "\n" 'and invoice as proof of purchase')
print('--------------------------------------------')
print('Due to implement of GST , such exchange' "\n" 'is permitted only at the store from where' "\n" 'merchandise is purchased')
print('--------------------------------------------')
print('For points balance SMS LANDMARK to 56767' "\n" 'od login to www.landmarkrewards.in' "\n" "It's a computer Generated Invoice" "\n" 'Original/Customer opy')
